//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttenRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int ID_History { get; set; }
        public string BarCode { get; set; }
        public byte[] picture { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> searchdate { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
